spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formwork
    username: formwork
    password: formwork
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  formwork:
    sms-channel:
      provider: TWILIO
      twilio:
        account-sid: AC123
        auth-token: token
        from-number: +15551234567